### ISSUE TITLE
does not run on Linux

### ISSUE THREAD

**Issue by luggels** [ZUGFeRD/quba-viewer#22]
quba_viewer-1.2.0.AppImage doesn't run on Ubuntu 22.04LTS, quits with the first line (xxx not found)

also can't install from github-repo, too many dependencies can't be resolved

I give up.

**Comment by jstaerk** [comment]
My bad, apologies, no idea how that got corrupted but it was. Now the download should work after chmodding it +x. Apparently in ubuntu you still need to install libfuse2 to run AppImages at all, though.

**Comment by olafdietsche** [comment]
This still doesn't work with release 1.4.0 on Ubuntu 22.04.

I installed Quba-1.4.0.AppImage in a minimal Docker container created by debootstrap.
When starting it requests libfuse2, and after that it fails because of missing fusermount.
But even after adding these two packages, it won't start, because it is requesting library after library, libglib, libnss, libatk, libatk-bridge, and so on ...
Only after resolving all the missing libraries, it starts up, sort of.

So, in the end there's nothing left from "download Appimage, make it executable, and enjoy" ;-)
